# -*- coding: utf-8 -*-
"""packages.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qy4r1ABFFbup320kfDUivP1Fzt3H9mAP
"""

# Commented out IPython magic to ensure Python compatibility.
# # Install rdkit
# %%capture
# !pip install rdkit-pypi
# import os
# 
# # Temporary suppress tf logs
# os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
# 
# import numpy as np
# import pandas as pd
# import matplotlib.pyplot as plt
# import tensorflow as tf
# from tensorflow import keras
# from tensorflow.keras import layers
# import warnings
# from rdkit import Chem
# from rdkit import RDLogger
# from rdkit.Chem.Draw import IPythonConsole
# from rdkit.Chem.Draw import MolsToGridImage
# 
# # Temporary suppress warnings and RDKit logs
# warnings.filterwarnings("ignore")
# RDLogger.DisableLog("rdApp.*")
# 
# np.random.seed(42)
# tf.random.set_seed(42)